name: Automatic deletion of resources

on:
  workflow_dispatch:
  push:
# env:
#   IAC_RESOURCE_GROUP_NAME: "backstage-be" # these envs can get turned into secrets, more of a preference really





jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Terraform
        shell: bash
        run: | 
        ssh 

